const StudySpots = [
    {
        id: "1",
        name: "The Egg",
        imageLink: "UBC_Nest_Egg.jpg",
        lat: 49.265999,
        long:-123.248489,
        ratingIds: [],
        filters: [],
    },
    {
        id: "2",
        name: "Forestry Building",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: ['quiet'],
    },
    {
        id: "3",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    },
    {
        id: "4",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    },
    {
        id: "5",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    },
    {
        id: "6",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    },
    {
        id: "7",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    },
    {
        id: "8",
        name: "TBD",
        imageLink: "ForestCenter.jpg",   
        lat: 49.260029,
        long:-123.248642,
        ratingIds: [],
        filters: [],
    }
]

export default StudySpots;